# Generated by Django 5.0.3 on 2024-05-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='taste',
        ),
        migrations.AddField(
            model_name='fruit',
            name='is_delicious',
            field=models.BooleanField(default=True),
        ),
    ]
