# Generated by Django 5.0.3 on 2024-05-01 09:05

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
            ],
            managers=[
                ('my_manage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
