# Generated by Django 5.0.3 on 2024-05-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_cake_rename_student_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('history', models.TimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='join_data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model_app.school'),
        ),
    ]
