# Generated by Django 5.0.3 on 2024-05-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0003_school_students_join_data_students_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='history',
            field=models.TextField(null=True),
        ),
    ]
