# Generated by Django 5.0.3 on 2024-05-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('score', models.FloatField(verbose_name='成绩')),
            ],
            options={
                'verbose_name': '学生表 (缓存)',
                'verbose_name_plural': '学生表 (缓存)',
            },
        ),
    ]
