# Generated by Django 5.0.3 on 2024-05-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
